### ISSUE TITLE
Odd decoding behavior

### ISSUE THREAD

**Issue by falun** [go-playground/form#1]
Hi there!

First off thanks for this -- it solves a problem I was about to have with `gorilla/schema` (lack of keyed map support) but I hit a different problem with `form`.

I've attached what I'm pretty sure this is an error case but I could be using it incorrectly, would appreciate some guidance.  The tl;dr is that when you have a slice of a struct there seems to be a different decoding behavior for populating an element than if you're reading directly into the same struct. Here's a repro case:

```go
package main

import (
	"fmt"

	"github.com/go-playground/form"
)

type Struct1 struct {
	Foo string
}

type Struct1Wrapper struct {
	InnerSlice []Struct1
}

type Struct2 struct {
	Foo string
	Bar string
}

type Struct2Wrapper struct {
	InnerSlice []Struct2
}

func main() {
	sliceValues := map[string][]string{
		"InnerSlice[0].Foo": {"foo-is-set"},
	}

	singleValues := map[string][]string{
		"Foo": {"foo-is-set"},
	}

	fd := form.NewDecoder();

	dst := Struct2Wrapper{}
	err := fd.Decode(&dst, sliceValues)
	fmt.Println(err)
	fmt.Printf("%#v\n", dst)

	dst2 := Struct2{}
	err = fd.Decode(&dst2, singleValues)
	fmt.Println(err)
	fmt.Printf("%#v\n", dst2)

	fmt.Println()
	fmt.Println()
	fmt.Println()

	dst3 := Struct1Wrapper{}
	err = fd.Decode(&dst3, sliceValues)
	fmt.Println(err)
	fmt.Printf("%#v\n", dst3)

	dst4 := Struct1{}
	err = fd.Decode(&dst4, singleValues)
	fmt.Println(err)
	fmt.Printf("%#v\n", dst4)
}
```

And the output, when run:

```
$ go install test && ./test
<nil>
main.Struct2Wrapper{InnerSlice:[]main.Struct2(nil)}
<nil>
main.Struct2{Foo:"foo-is-set", Bar:""}



<nil>
main.Struct1Wrapper{InnerSlice:[]main.Struct1{main.Struct1{Foo:"foo-is-set"}}}
<nil>
main.Struct1{Foo:"foo-is-set"}
```

I could also be doing something goofy in my test code. _Shrug_, 😄 

Might try to take a look at this myself but I assume it'll be a much faster debug & fix from someone who already knows the codebase.

**Comment by joeybloggs** [comment]
I will look into this right away, strange that the first case is not set.
```go
<nil>
main.Struct2Wrapper{InnerSlice:[]main.Struct2(nil)}
```

**Comment by joeybloggs** [comment]
Thanks for this @falun 

it was an issue with the traverseStruct, I only set values when fields exist and was setting the bool that tells the calling func to set the value or not on every field of the struct; since `Struct2.Bar` returned false, the value was not set, even though it was created. I have corrected to return true to set if any field was valid.

fixed in commit d77a15c9ed9b21e97f6587bae863b6f9213f7c2b

if you could please confirm the fix works for you.

**Comment by falun** [comment]
Wooo. Awesome turn around, thanks :)

Ran through my test to verify it works as expected. Will pipe up if I hit anything as I start trying to integrate into my actual codebase.

**Comment by joeybloggs** [comment]
Fantastic and thanks again.

If you also need validation for those newly decoded Struct values you can take a look my validator library if your interested; it's low level and handles anything you can throw at it.
