### ISSUE TITLE
How to add a new item to a slice?

### ISSUE THREAD

**Issue by danhardman** [go-playground/form#11]
In a HTML form, how do I represent a new (to be added) item for a slice?

I've tried `name="Languages[].Country"`, where the index isn't defined. As well as providing an index that doesn't exist, neither seem to work.

**Comment by joeybloggs** [comment]
Hey @danhardman would you be able to provide a little more example code? It's hard to tell exactly what you're trying to accomplish without a little more context.

Eg. The Struct definition, is it being decoded into a struct, an array... that sort of thing

**Comment by danhardman** [comment]
@joeybloggs No problem.

```go
type User struct {
 Name string
 Languages []Language
}

type Language struct {
 Country string
}
```

Say I have a form to update a user, all `<input />` fields are constructed around User's struct definition, including all the languages the user knows in the form of:

```html
<input type="text" name="Languages[0].Country" value="{{ .Languages[0].Country }}" />
...
```

Where an indexed reference to each known language exists in the form. I can update pre-existing languages by editing the value and posting the form which decodes the form into the struct of a user and the pre-existing languages are updated.

What I'm struggling with though is how to decode **new** languages onto the user struct. So that `*form.Decoder.Decode()` appends a new item(s) onto the languages slice on the user struct.

**Comment by danhardman** [comment]
Fixed. Was my fault, specifying the input without an index does append the item onto the slice during decode.

I was simply passing the form as a `multipart/form-data` but not parsing it as such so the form was coming across empty.

**Comment by joeybloggs** [comment]
@danhardman glad you could solve your problem :smile: I think we all have these moments from time to time.
