### ISSUE TITLE
Registering multiple DecodeCustomTypeFuncs against a type

### ISSUE THREAD

**Issue by danhardman** [go-playground/form#12]
Is it possible to register multiple custom types on the same type? I want to accept multiple ways of passing a `time.Time` type in separate use cases.

I've tried registering them procedurally:

```go
decoder.RegisterCustomTypeFunc(func(vals []string) (interface{}, error) {
		return time.Parse("02/01/06 3:04 PM MST -0700", vals[0])
	}, time.Time{})
	decoder.RegisterCustomTypeFunc(func(vals []string) (interface{}, error) {
		return time.Parse("3:04 PM", vals[0])
	}, time.Time{})
```

And that didn't work, it tries to use the first one. If it's not currently possible, can this be a feature request? When multiple `DecodeCustomTypeFuncs` are registered to a type, you could iterate through them on parse error?

**Comment by joeybloggs** [comment]
Hey @danhardman 

I don't think it would be a good idea to register multiple, but rather, why not check both time formats in your custom function?

eg. if first time.Parse format fails, try the second

**Comment by danhardman** [comment]
@joeybloggs Hadn't actually thought of that. 

You know that moment when you get in the mindset of doing it the way the library and you forget about the language way? Maybe it's just me! haha should work fine, thank you!

**Comment by joeybloggs** [comment]
No problem @danhardman we all have those can't see the forest because of the trees moments ;)
