### ISSUE TITLE
Encode struct fields with `foo[bar]`

### ISSUE THREAD

**Issue by danielchatfield** [go-playground/form#17]
Whilst I understand why `foo.bar` may be preferable, it would be useful to be able to configure the encoder to output struct fields as `foo[bar]` is this is the format that lots of other systems expect (e.g. ruby).

Happy to submit a PR if you can point me in the right direction.

**Comment by joeybloggs** [comment]
Hi @danielchatfield 

I definitely want to keep the default working as is, but am open to different output modes; I'll need a little more information though, like:

- Does or how does ruby handle or need it formatted for nested structs?
- How does ruby handle arrays and maps?

Any other information would be helpful :smile:

**Comment by deankarn** [comment]
This should now be closed by #56
