### ISSUE TITLE
Support "omitempty" on form tag

### ISSUE THREAD

**Issue by michael2m** [go-playground/form#18]
Support `form:"foo,omitempty"` to skip default values from encoding/decoding. This aligns e.g. with JSON encoding/decoding behavior.

**Comment by joeybloggs** [comment]
Just to confirm you mean for the encoder portion?

great idea for an enhancement :) I'll look into it

**Comment by joeybloggs** [comment]
@michael2m this feature has been added in [release 3.0.0](https://github.com/go-playground/form/releases/tag/v3.0.0)
