### ISSUE TITLE
Support embedded structs

### ISSUE THREAD

**Issue by danielchatfield** [go-playground/form#19]
I think it is desirable for the behaviour of decoding into `A` and `B` to be identical. I.e. fields of embedded structs are treated as if they were fields of the outer struct.
```
type A struct {
    Field string
}

type B struct {
    A
}

**Comment by joeybloggs** [comment]
Thanks @danielchatfield 

I'll check into this, might be a little while and I have to make Decode changes as well and deal with these sorts of scenarios:
```
type A struct {
	Field string
}

type B struct {
	A
	Field string
}
```

P.S. sorry for the lateness of my reply, super busy with new job and moving.

**Comment by danielchatfield** [comment]
>P.S. sorry for the lateness of my reply, super busy with new job and moving.

**Comment by joeybloggs** [comment]
@danielchatfield this feature has been added in [release 3.0.0](https://github.com/go-playground/form/releases/tag/v3.0.0)
