### ISSUE TITLE
Multipart Form Support

### ISSUE THREAD

**Issue by sunfmin** [go-playground/form#23]
Client posted JavaScript `FormData` object, which will be put into https://golang.org/pkg/mime/multipart/#Form

Which should properly converted to struct like?

```go

type User struct {
	Name        string
	Age         uint8
        Avatar      *multipart.FileHeader
}

```

**Comment by joeybloggs** [comment]
Hey @sunfmin currently this library only deals with the `Form.Value` portion of the [Form](https://golang.org/pkg/mime/multipart/#Form) which is actually a https://golang.org/pkg/net/url/#Values

There are several reasons for that:
- wanted to keep it generic so it works with and `url.Values` including `http.Request.Form` and `http.Request.PostForm`
- most people are going to handle files differently and have different size limits and logic surrounding files and so did not attempt to presume on handling that for everyone.

I hope I'm explaining myself properly, please let me know :)
