### ISSUE TITLE
Parse string/int into interface{} ?

### ISSUE THREAD

**Issue by Xzya** [go-playground/form#25]
Hello,

I need to support an older version of an API which supported both `application/json` and `application/x-www-form-urlencoded` requests, and some of the request parameters had inconsistent types, e.g. it could be sent as a number or a numeric string. So in order to support both json and forms, as well as numeric strings and numbers, I changed the parameter type to `interface{}`, however, it is always decoded as `nil`, presumably because the form type and the target value type do not match (e.g. int/string != interface{}), but I would expect that if I have a parameter of type `interface{}`, and that parameter is found in the form, then it would store the value in the parameter, since it can hold anything.

Here is an example:

```go
package main

import (
	"bytes"
	"net/url"
	"fmt"
	"io"
	"github.com/go-playground/form"
)

type V1Request struct {
	Application interface{} `json:"application"`
	DeviceModel string      `json:"deviceModel,omitempty"`
}

func UrlformConsumerFunc() func(reader io.Reader, v interface{}) error {
	// create a new form decoder
	decoder := form.NewDecoder()

	// change tag to json since it's added by default by goswagger
	decoder.SetTagName("json")

	return func(r io.Reader, v interface{}) error {
		buf := new(bytes.Buffer)
		buf.ReadFrom(r)

		values, err := url.ParseQuery(buf.String())
		if err != nil {
			return err
		}

		return decoder.Decode(v, values)
	}
}

func main() {
	consumer := UrlformConsumerFunc()
	req := V1Request{}

	query := bytes.NewBufferString("application=5&deviceModel=iPhone")
	consumer(query, &req)

	fmt.Printf("Converted value %#v\n", req)
}
```

The output of this will be:

```
Converted value main.V1Request{Application:interface {}(nil), DeviceModel:"iPhone"}
```

Is there any way to achieve this using the library?

Thanks!

**Comment by joeybloggs** [comment]
Hey @Xzya thanks for asking/reporting I think it's getting stuck [here](https://github.com/go-playground/form/blob/master/decoder.go#L208) because of the field type being interface.

I can definitely see how this would be useful in your scenario, I'll look at updating the code to just set the value when the kind/type is `interface{}`; it may be a few days though.

hang tight 😄

**Comment by joeybloggs** [comment]
@Xzya just letting you know I haven’t forgotten about this, just been super busy.

**Comment by Xzya** [comment]
Hey @joeybloggs,

No worries. I currently have an ugly patch in place using reflection, but it would be nice for the library to do this automatically.

```go
// SetFieldValue sets the `field` of `v` to `value`. Only works if the field exists
// and is exported on `v`, and if `value` is assignable to `field` (e.g. if `field`
// and `value` have the same type, or if `field` is `interface{}`).
func SetFieldValue(value interface{}, field string, v interface{}) {
	// make sure v is a pointer
	k := reflect.TypeOf(v).Kind()
	if k == reflect.Ptr {
		// pointer to struct - addressable
		ps := reflect.ValueOf(v)
		// struct
		s := ps.Elem()
		if s.Kind() == reflect.Struct {
			f := s.FieldByName(field)
			if f.IsValid() {
				// A Value can be changed only if it is
				// addressable and was not obtained by
				// the use of unexported struct fields.
				if f.CanSet() {
					// change value of the field
					if (f.Kind() == reflect.TypeOf(value).Kind()) || (f.Kind() == reflect.Interface) {
						f.Set(reflect.ValueOf(value))
					}
				}
			}
		}
	}
}

func UrlformConsumerFunc() runtime.ConsumerFunc {
	// create a new form decoder
	decoder := form.NewDecoder()

	// change tag to json since it's added by default by goswagger
	decoder.SetTagName("json")

	return func(r io.Reader, v interface{}) error {
		buf := new(bytes.Buffer)
		buf.ReadFrom(r)

		values, err := url.ParseQuery(buf.String())
		if err != nil {
			return err
		}

		if err := decoder.Decode(v, values); err != nil {
			return err
		}

		// patch for `application` field not being parsed into `interface{}` fields
		app := values.Get("application")
		if len(app) > 0 {
			SetFieldValue(app, "Application", v)
		}

		return nil
	}
}
```

Thanks!

**Comment by joeybloggs** [comment]
@Xzya I added setting of form values, string only, into interface values in [release 3.1.0](https://github.com/go-playground/form/releases/tag/v3.1.0)

unfortunately unlike in JSON where we can know if it's a number or string value because of it's quoted there is just no way for the library to tell what it should be, so I'm only setting the string value.

Let me know if this works for you :)

**Comment by Xzya** [comment]
Looks good, thank you!
