### ISSUE TITLE
Support for multipart/form-data? Yes

### ISSUE THREAD

**Issue by MattDavisRV** [go-playground/form#3]
Do you have any plans to support multipart/form-data and file uploads with this package?

**Comment by joeybloggs** [comment]
I am investigating adding a separate function to aid in extracting file uploads, but not directly in the Decode portion, too many variables like some people may want to store file in Struct, others not and on disk but store file details....

As for multiparty/form-data, it already supports it! :), [here is a link](https://github.com/go-playground/lars/blob/master/context.go#L456) to my lars router and how it uses this library for multipart forms.

essentially you just have to call it like so:
```go
if err := request.ParseMultipartForm(maxMemory); err != nil {
	return err
}

err = decoder.Decode(&structval, request.MultipartForm.Value)
```

**Comment by joeybloggs** [comment]
Did this work for you @MattDavisRV ?

**Comment by joeybloggs** [comment]
Closing due to lack of response.
