### ISSUE TITLE
Single array param set all elements instead of one

### ISSUE THREAD

**Issue by powerman** [go-playground/form#33]
```go
func TestDecodeArrayBug33(t *testing.T) {
	var data struct {
		A [3]string
	}
	cases := []struct {
		values url.Values
		want   [3]string
	}{
		{url.Values{"A": {"10"}},
			[3]string{"10", "", ""}},   // Output: [10 10 10]
		{url.Values{"A": {"10", "20"}},
			[3]string{"10", "20", ""}}, // Output: [10 10 10]
		{url.Values{"A[1]": {"20"}},
			[3]string{"", "20", ""}},   // Output: [ 20 ]
		{url.Values{"A": {"10"}, "A[2]": {"30"}},
			[3]string{"10", "", "30"}}, // Output: [10 10 30]
	}
	for _, v := range cases {
		data.A = [3]string{}
		form.NewDecoder().Decode(&data, v.values)
		t.Log(data.A)
	}
}
```

**Comment by powerman** [comment]
3rd case is correct, btw, it was included just in case.

**Comment by joeybloggs** [comment]
Thanks I noticed and already fixing

**Comment by powerman** [comment]
Actually I believe mixing `array/slice` with `array/slice[idx]` should be illegal. As order of keys in url.Values is undefined decoding params `var=10&var[0]=20` may result either in `[20]` or in `[20,10]`. (My strict checker in https://github.com/powerman/urlvalues already return error in this case, but this should be implemented in form too.)

**Comment by joeybloggs** [comment]
Actually, in the library it should be determined, I set it up to process `array/slice` first then it assigns`array/slice[idx]` as they are obviously more specific.

although it's not likely or recommended to mix, I will support it because internally it is ordered, otherwise I would agree with you.
