### ISSUE TITLE
Missing pointer value "0" while encoding struct

### ISSUE THREAD

**Issue by mifanich** [go-playground/form#34]
type T struct {
	X *uint8 `form:"x,omitempty"`
}

func main() {
	tx := uint8(0)
	x := T{&tx}
	encoder := form.NewEncoder()
	values, _ := encoder.Encode(x)
	fmt.Println(values) // blank map
}

If I try to set value to 0, encoder ignores this field

**Comment by joeybloggs** [comment]
Thanks @mifanich for reporting, I suspect  it's a bug in the omitempty logic thinking 0 is the default value after dereference, hopefully just an order of operations issue.

**Comment by mifanich** [comment]
@joeybloggs  When do you plan to fix it

**Comment by joeybloggs** [comment]
As soon as I find time, hopefully this evening after work.

**Comment by mifanich** [comment]
thank you very much

**Comment by joeybloggs** [comment]
@mifanich  this should be fixed in v3.1.3 release, please let me know :)

**Comment by mifanich** [comment]
It works now. Thanks!
