### ISSUE TITLE
How does it compare with go-query/ gorilla schema?

### ISSUE THREAD

**Issue by themihai** [go-playground/form#5]
https://github.com/gorilla/schema
https://github.com/google/go-querystring

**Comment by joeybloggs** [comment]
There is a link in the README to competitor benchmarks, which includes gorilla schema, here it is for convenience [benchmarks](https://github.com/go-playground/form/blob/master/benchmarks/benchmarks.md)

As for go-querystring I'll have to add some benchmarks, keeping in mind that form also does decoding as well as encoding

**Comment by themihai** [comment]
It seems the syntax is also different.(e.g. gorilla schema doesn't require brackets on slices/arrays )

**Comment by joeybloggs** [comment]
Hey @themihai 

just so you know brackets on slices/arrays are not required, that is just an option both the normal form and bracketed arrays are supported

**Comment by themihai** [comment]
I've tested `&Phones.0.Label=x&Phones.0.Number=1&Phones.1.Label=y&Phones.2.Label=z&Phones.2.Number=3` and it failed to decode it. Do you mean slices without brackets and without indexes too ? 
I think without indexes the data structure is getting messed up because the map keys are unordered. How would the the query below decode? 
`&Phones.Label=x&Phones.Number=1&Phones.Label=y&Phones.Label=z&Phones.Number=3`

```
 type Phone struct{
      Number int
      Label string
 }
   type T struct{
      Phones Phones
  }

**Comment by joeybloggs** [comment]
@themihai , sorry I misunderstood yes it supports slices without brackets or indexes

but if you are trying to fill an array of a complex type i.e. `struct` then brackets with indexes are required.

i.e. if trying to populate a simple array of `Label []string`
`&Label=lbl1&Label=lbl2...`
