### ISSUE TITLE
What about supporting case-insensitive key?

### ISSUE THREAD

**Issue by Loyalsoldier** [go-playground/form#58]
### Package version eg. v9, v10: 

v4

### Issue, Question or Enhancement:

I want these two requests work at the same time:

```
curl host/api?queryTime=timestamp
curl host/api?querytime=timestamp
```

In other words, what about supporting case-insensitive key?

### Code sample, to showcase or reproduce:

```go
type Request struct {
  queryTime string `form:"queryTime"`
}

var req Request
decode.Decode(&req, r.Form)
```

**Comment by WineChord** [comment]
@Loyalsoldier  Why is this closed? Do you find any possible approach towards supporting case-insensitive key?
