### ISSUE TITLE
slice, array:  interface must be a pointer to a struct

### ISSUE THREAD

**Issue by themihai** [go-playground/form#6]
It seems slice and array types are supported only on struct properties.

**Comment by joeybloggs** [comment]
Hey @themihai 

currently that is correct, as the description states `Package form Decodes url.Values into struct values`

however, it actually might not be that hard to also decode directly into variables such as arrays or maps.

I will look into the possibility of adding this tonight after I get off work; thanks for the idea.

**Comment by themihai** [comment]
You're right! I was quick to jump on the "Supported Types" section instead to read documentation more thoroughly.  Support for direct values would be nice as it would put query encoding on par with the other formats(i.e. json).

**Comment by themihai** [comment]
I've tried a quick  decoding implementation of direct struct slices(just[ hooked-up t](https://github.com/go-playground/form/compare/master...themihai:master#diff-55a9605dc991cf8a53157ad108bb9968L111)he slice decoding method into the main Decode function) but unfortunately some tests([see the commented out lines](https://github.com/go-playground/form/compare/master...themihai:master#diff-d477aef9bf305a8d89d0973a5b775b8aR783)) are failing. These seem to be related to maps and arrays of the struct properties so I guess I'm missing some important steps in the decoding process.

**Comment by joeybloggs** [comment]
Hey @themihai 

It is a good attempt, I think you just may be overcomplicating it; all of the logic already exists to parse slices and maps, what I was thinking was change [this line](https://github.com/go-playground/form/blob/master/form_decoder.go#L112) to call [setFieldByType](https://github.com/go-playground/form/blob/master/decoder.go#L172)

and the rest should handle itself, at least that's the theory ;)

**Comment by joeybloggs** [comment]
Hey @themihai just an FYI, I've completed the Decoder portion of these changes and if all goes well will finish up making the same changes to Encoder in the morning.

**Comment by themihai** [comment]
Indeed, it was easier than I thought!  Looking forward for the updates! With this change the encoder supports pretty much any valid data type including basic types.

**Comment by joeybloggs** [comment]
Hey @themihai this change has been made is in [Release 2.0.0](https://github.com/go-playground/form/releases/tag/v2.0.0)

if there are any issues please don't hesitate to reopen.

**Comment by joeybloggs** [comment]
Hey @themihai just checking to make sure this is working out for you?
