### ISSUE TITLE
Decode form to specific field?

### ISSUE THREAD

**Issue by danhardman** [go-playground/form#9]
Say I have the following struct:

```go
type User struct {
 Address Address
}
```

Am I able to decode form data to only the `Address` field? Like so:

```go
decoder = form.NewDecoder()
r.ParseForm()
var user User

if err := decoder.Decode(&user.Address, r.Form); err != nil {
 panic(err)
}
```

Assuming the form data provided is in a suitable format for the `User` struct.

**Comment by joeybloggs** [comment]
Hey @danhardman 

it depends, if the form values are passed down in the form `Address.City` then yes it will work like you want.

however if the values are passed down in form `User.Address.City` then it will never match the struct namespace to the url key values; and as you mentioned the form data provided would be in the format for `User` and so it would not work.

Am I right in assuming that you just don't want to also decode the other user info that may be posted down? if so then you can create another User struct with only the Address field, like you specified above. and can pass in `&user`

**Comment by danhardman** [comment]
@joeybloggs Yes, I would be creating the form for the user, so I'd have fields like:

```html
<input type="text" name="Name" />
<input type="text" name="Address.Address1" />
<input type="text" name="Address.Address2" />
<input type="text" name="Address.City" />
```

But for this example, say I only want the request to update the User's address. I'd like to do

```go
if err := decoder.Decode(&user.Address, r.Form); err != nil {
 panic(err)
}
```

I'd prefer not to have to create a separate struct, even if it was anonymous, simply because I may have to do this quite a bit and it would get tedious

**Comment by joeybloggs** [comment]
@danhardman 

your HTML would have to be like:
```html
<input type="text" name="Address1" />
<input type="text" name="Address2" />
<input type="text" name="City" />
```

form starts at the field level with structs.

**Comment by danhardman** [comment]
@joeybloggs 

Ah that's what I figured, no problem. Thanks!

**Comment by joeybloggs** [comment]
@danhardman glad I could help 😄  don't hesitate to ever ask anything ( can't promise to always be this prompt but... )

**Comment by danhardman** [comment]
@joeybloggs Honestly I'm amazed at the responses I've been getting on this repo. Others aren't nearly as helpful! Hopefully I can spend more time contributing instead of creating issues in future ;)
